# Generated by Django 3.2.5 on 2021-07-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210728_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='FIELDNAME',
            new_name='job',
        ),
    ]
