# Generated by Django 3.2.5 on 2021-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_auto_20210802_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nombre Completo'),
        ),
    ]
